services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: local
    volumes:
      - .:/var/www:rw
      - /var/www/vendor
    working_dir: /var/www
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - APP_PORT=${APP_PORT:-1337}
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '${APP_PORT:-1337}:${APP_PORT:-1337}'
    depends_on:
      - mysql
    networks:
      - phenix

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-phenix}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - phenix

volumes:
  mysql_data:

networks:
  phenix:
    driver: bridge