#!/usr/bin/env php

<?php

use Core\App;
use Core\Console\Phenix;

require_once __DIR__ . '/vendor/autoload.php';

require_once __DIR__ . '/core/bootstrap.php';

/** @var \Core\Console\Phenix $phenix */
$phenix = App::make(Phenix::class);

$phenix->run();