#!/usr/bin/env php

<?php

define('APP_PATH', __DIR__);

require __DIR__ . '/vendor/autoload.php';

use Core\Console\Phenix;

$application = new Phenix();

$application->loadCommands();

$application->run();