#!/usr/bin/env php

<?php

use Phenix\App;
use Phenix\Console\Phenix;

require_once __DIR__ . '/vendor/autoload.php';

require_once __DIR__ . '/bootstrap/app.php';

/** @var \Phenix\Console\Phenix $phenix */
$phenix = App::make(Phenix::class);

$phenix->run();
